### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_jayg_ppi2020#10]

**Comment by 0XsamuelX0** [comment]
https://fotos.subefotos.com/b082e802b49a6cb19f48664fa7d84be3o.png´
https://fotos.subefotos.com/614181a598e89112fdcebde7b6d9a0e0o.png
https://fotos.subefotos.com/d802eef802f67f06103f45d605cfcfc6o.png
https://fotos.subefotos.com/48cca087da0dc19ad3411a49a70373dbo.png
https://fotos.subefotos.com/81459eb8f38196b7d5bf9d3936a5bbc4o.png

**Comment by 0XsamuelX0** [comment]
https://fotos.subefotos.com/b082e802b49a6cb19f48664fa7d84be3o.png
https://fotos.subefotos.com/614181a598e89112fdcebde7b6d9a0e0o.png
https://fotos.subefotos.com/d802eef802f67f06103f45d605cfcfc6o.png
https://fotos.subefotos.com/48cca087da0dc19ad3411a49a70373dbo.png
https://fotos.subefotos.com/81459eb8f38196b7d5bf9d3936a5bbc4o.png

**Comment by JohnFlorez25** [comment]
@0XsamuelX0 acá estaban los prototipos, listo, cumples con lo proyectado, nos faltan los de alta fidelidad en la wiki y en la actividad.
