### ISSUE TITLE
- [ ] Realizar validaciones con 5 usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_jayg_ppi2020#11]

**Comment by 0XsamuelX0** [comment]
https://fotos.subefotos.com/a58321af5130b8a0256b113ac201a5efo.png

https://fotos.subefotos.com/6f66043e2d5df3f471a973dc3ec0660do.png

https://fotos.subefotos.com/c8454a81a55efa986119dbd83199382bo.png

https://fotos.subefotos.com/4863aaad4d253ec2064365a87f34d9dco.png

https://fotos.subefotos.com/a2161318fba5db9e27a8560fef6936afo.png
