### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_jayg_ppi2020#2]

**Comment by 0XsamuelX0** [comment]
![DIAGRAMA DE ISHIKAWA](https://user-images.githubusercontent.com/66139788/88247318-f35c5f80-cc62-11ea-8029-b95d2911aceb.png)

**Comment by 0XsamuelX0** [comment]
![DIAGRAMA DE ISHIKAWA](https://user-images.githubusercontent.com/66139788/88247339-040cd580-cc63-11ea-973c-8f234a5023db.png)

**Comment by 0XsamuelX0** [comment]
https://fotos.subefotos.com/27b84c8e347fccefa5ffc1001c319153o.png

**Comment by JohnFlorez25** [comment]
Ok
